version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"   # native driver
      - "8123:8123"   # HTTP interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""

  ticker:
    build: .
    depends_on:
      - clickhouse
    environment:
      OUTPUT_MODE: clickhouse
      CLICKHOUSE_HOST: clickhouse
    restart: unless-stopped

volumes:
  clickhouse-data:
